### ISSUE TITLE
Not responsive on smaller screens

### ISSUE THREAD

**Issue by ghost** [sami-ul-haq/snake-game-javascript#1]
The game is amazing however it is not responsive on smaller screens. Try out media queries to fit the canvas in the vw and vh of the device. Also add padding to the text content/instructions written on the right of the game.

**Comment by sami-ul-haq** [comment]
> The game is amazing however it is not responsive on smaller screens. Try out media queries to fit the canvas in the vw and vh of the device. Also add padding to the text content/instructions written on the right of the game.

Made Responsive, Fixed.
